### ISSUE TITLE
pbcorethat description - additional descriptive and technical fields

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#15]
Please move the Additional Descriptive and Additional Technical fields to below the Main Title and Description or Content Summary.

**Comment by dericed** [comment]
do you mean "Additional Descriptive Notes for Overall Work" and "Additional Technical   Notes for Overall Work"?

**Comment by dericed** [comment]
ok, i see those two fields were mapped to identifiers, now they are descriptions in https://github.com/cavpp/cavppers/pull/25
