### ISSUE TITLE
pbcorethat - descriptive - date

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#16]
- Date Created is showing up as Date Published still.

**Comment by klipska** [comment]
- Date formatting is all crazy. This may be because the export .csv was opened at some point. I'm hoping if we export without ever opening the CSV date will stay ok. I tried to test, but I couldn't get it to work again. Will retest when updated.

**Comment by dericed** [comment]
ha, `export without ever opening the CSV date` isn't really ideal, should be able to detect whatever weirdo thing excel feels like doing to mangle our data.

**Comment by dericed** [comment]
so weird, I think I just had `Date Created` and `Date Published` swapped. fixed locally.
