### ISSUE TITLE
pbcorethat - technical - validation

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#19]
PBCore does not validate. In addition to the lines with problems that Oxygen points out, I think Identifier, Title and Description will need to be repeated after PBCorePart in order to validate.

**Comment by dericed** [comment]
a few reasons that the pbcore is invalid.

1. Both `Institution` and `Institution URL` are mapped to @collectionSource, but there can only be once. Temporarily I used @collectionSource and @collectionSourceAGAIN (which is invalid). Which value is intended to map to @collectionSource?

**Comment by dericed** [comment]
2. We currently don't have an instantiationIdentifier for the instantiation referenced by the `Gauge and Format` column. What can we use for that identifier?

**Comment by klipska** [comment]
1. collectionsource should be Institution. Let's use this for Institution URL: <pbcoreIdentifier source="Institution" annotation="Institution URL">https://someinstitutionURL.com</pbcoreIdentifier>
2. Is this the <instantiationPhysical> v.s. <instantiationDigital> question? Are there any other options of what to call this so that it could refer to either an original physical format OR to a born digital file? If not, is there a way we can direct the script to use one tag or another when we run it?

**Comment by dericed** [comment]
i think everything here is covered in https://github.com/cavpp/cavppers/pull/33/commits. I used the object id for the instantiation of the original object so that looks like:

```
    <pbcoreInstantiation>
      <instantiationIdentifier source="CAVPP" annotation="Object Identifier">cabesc_000001</instantiationIdentifier>
      <instantiationPhysical>mp4</instantiationPhysical>
      <instantiationLocation>XYZ Place</instantiationLocation>
      <instantiationMediaType>Moving Image</instantiationMediaType>
      <instantiationGenerations>Copy</instantiationGenerations>
      <instantiationColors>Color</instantiationColors>
      <instantiationTracks>Sound</instantiationTracks>
      <instantiationLanguage>eng</instantiationLanguage>
      <instantiationAnnotation source="Total Number of Reels or Tapes">1 File of 1</instantiationAnnotation>
    </pbcoreInstantiation>
```
