### ISSUE TITLE
pbcorethat - technical - checksum info

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#22]
Actual checksum data is missing. Do something like this:

`<pbcoreInstantiation>
            <instantiationIdentifier source="California Revealed" annotation="file name">cma_000075_prsv.mov</instantiationIdentifier>
            <instantiationIdentifier source="California Revealed" version="MD5" annotation="checksum">BCD1C27DCE98D9C20EE63619D0C8DB87</instantiationIdentifier>`

But please use line breaks after closed tags. It makes it easier to read.

**Comment by dericed** [comment]
Is the name of the md5 predictable from the file it depicts? Would the md5 of `a_prsv.mov` be `a_prsv.mov.md5`?

**Comment by klipska** [comment]
Yes
