### ISSUE TITLE
review mapping

### ISSUE THREAD

**Issue by dericed** [cavpp/cavppers#30]
some of the column assignments changed since this work started, we should review the current mapping. Please note other columns that should be mapped or mappings that need to be fixed (transcript?).

|                                                              |    |                          | 
|--------------------------------------------------------------|----|--------------------------| 
| Internet Archive URL                                         | 1  | identifiers              | 
| Object Identifier                                            | 2  | identifiers              | 
| Call Number                                                  | 3  | identifiers              | 
| Project Identifier                                           | 4  | identifiers              | 
| Project Note                                                 | 5  | extension                | 
| Institution                                                  | 6  | instantiationlocation    | 
| Asset Type                                                   | 7  | AssetType                | 
| Media Type                                                   | 8  | instantiationmediatype   | 
| Generation                                                   | 9  | instantiationgenerations | 
| Main or Supplied Title                                       | 10 | titles                   | 
| Additional Title                                             | 11 | titles                   | 
| Series Title                                                 | 12 | titles                   | 
| Description or Content Summary                               | 13 | descriptions             | 
| Why the recording is significant to California/local history | 14 |                          | 
| Creator                                                      | 15 | creator                  | 
| Producer                                                     | 16 | creator                  | 
| Director                                                     | 17 | creator                  | 
| Writer                                                       | 18 | creator                  | 
| Interviewer                                                  | 19 | creator                  | 
| Performer                                                    | 20 | creator                  | 
| Country of Creation                                          | 21 | extension                | 
| Date Created                                                 | 22 | Date                     | 
| Date Published                                               | 23 | Date                     | 
| Copyright Statement                                          | 24 | rights                   | 
| Gauge and Format                                             | 25 | instantiationphysical    | 
| Total Number of Reels or Tapes                               | 26 | instantiationannotation  | 
| Duration                                                     | 27 |                          | 
| Silent or Sound                                              | 28 | instantiationtracks      | 
| Color and/or Black and White                                 | 29 | instantiationcolors      | 
| Contributor                                                  | 30 | contributor              | 
| Camera                                                       | 31 | contributor              | 
| Editor                                                       | 32 | contributor              | 
| Sound                                                        | 33 | contributor              | 
| Music                                                        | 34 | contributor              | 
| Cast                                                         | 35 | contributor              | 
| Interviewee                                                  | 36 | contributor              | 
| Speaker                                                      | 37 | contributor              | 
| Musician                                                     | 38 | contributor              | 
| Publisher                                                    | 39 | publisher                | 
| Distributor                                                  | 40 | publisher                | 
| Language                                                     | 41 | instantiationlanguage    | 
| Subject Topic                                                | 42 | subjects                 | 
| Subject Entity                                               | 43 | subjects                 | 
| Genre                                                        | 44 |                          | 
| Spatial Coverage                                             | 45 | genre                    | 
| Temporal Coverage                                            | 46 |                          | 
| Collection Guide Title                                       | 47 |                          | 
| Collection Guide URL                                         | 48 |                          | 
| Relationship                                                 | 49 |                          | 
| Relationship Type                                            | 50 |                          | 
| Aspect Ratio                                                 | 51 |                          | 
| Running Speed                                                | 52 |                          | 
| Timecode Content Begins                                      | 53 |                          | 
| Track Standard                                               | 54 |                          | 
| Channel Configuration                                        | 55 |                          | 
| Subtitles/Intertitles/Closed Captions                        | 56 |                          | 
| Stock Manufacturer                                           | 57 |                          | 
| Base Type                                                    | 58 |                          | 
| Base Thickness                                               | 59 |                          | 
| Copyright Holder                                             | 60 | rights                   | 
| Copyright Holder Info                                        | 61 | rights                   | 
| Copyright Date                                               | 62 | rights                   | 
| Copyright Notice                                             | 63 | rights                   | 
| Institutional Rights Statement (URL)                         | 64 | rights                   | 
| Institution URL                                              | 65 |                          | 
| Quality Control Notes                                        | 66 |                          | 
| Additional Descriptive Notes for Overall Work                | 67 | descriptions             | 
| Additional Technical Notes for Overall Work                  | 68 | descriptions             | 
| Transcript                                                   | 69 | identifiers              | 
| Cataloger Notes                                              | 70 |                          | 
| Embedded Title                                               | 71 |                          | 
| Embedded Year                                                | 72 |                          | 
| Embedded Institution                                         | 73 |                          | 
| Embedded Comment                                             | 74 |                          | 
| Embedded Copyright                                           | 75 |                          | 
| Grant cycle                                                  | 76 |                          | 
| Workflow state                                               | 77 |                          |

**Comment by klipska** [comment]
Here are updates for anything thay was incorrect or missing.

Can Institution - 6 be mapped to instantiationlocation AND collectionSource?

Duration- 27 = instantiationDuration
Genre - 44 = pbcoreGenre
Spatial coverage - 45 = pbcoreCoverage `<coverageType>Spatial</coverageType>`
Temporal coverage - 46 = pbcoreCoverage `<coverageType>Temporal</coverageType>`
Collection Guide Title - 47 =collectionTitle
Collection Guide URL - 48 = collectionRef
Relationship - 49 = pbcoreRelation pbcoreRelationIdentifier
Relationship Type - 50 = pbcoreRelationType
Aspect Ratio - 51 = essenceTrackAspectRatio
Running Speed - 52 = essenceTrackPlaybackSpeed unitsOfMeasure="ips"
Timecode Content Begins - 53 = essenceTrackTimeStart
Track Standard - 54 = instantiationTracks
Channel Configuration - 55 = instantiationChannelConfiguration
Subtitles/Intertitles/Closed Captions - 56 = instantiationAlternativeModes  
Stock Manufacturer - 57 = instantiationAnnotation annotationType="Stock Manufacturer"
Base Type - 58 = instantiationAnnotation annotationType="Base Type"
Base Thickness - 59 = instantiationAnnotation annotationType="Base Thickness"
Institution URL - 65 = pbcoreIdentifier source="Institution" annotation="Institution URL"
Quality Control Notes - 66 = instantiationAnnotation annotationType="CA-R Quality Control"
Additional Technical Notes for Overall Work - 68 = instantiationAnnotation annotationType="Additional Technical Notes for Overall Work"
Transcript - 69 = pbcoreDescription descriptionType="Transcript"
Cataloger Notes - 70 = instantiationAnnotation annotationType="CatalogerNotes

The rest of those fields at the end, and 14, can be ignored.

**Comment by klipska** [comment]
Can you look at the xml samples I emailed you to see what sort of technical info about the files is included, and how it is mapped?

**Comment by klipska** [comment]
Some data didn't get mapped in the tests I did today.
Collection Guide info missing: 
Collection Guide Title - 47 =collectionTitle
Collection Guide URL - 48 = collectionRef

Genre missing: 
Genre - 44 = pbcoreGenre

**Comment by klipska** [comment]
Quality Control info is missing. Should be mapped like:

Quality Control Notes - 66 = instantiationAnnotation annotationType="CA-R Quality Control"

under the  instantiation.

**Comment by dericed** [comment]
quality control is added in https://github.com/cavpp/cavppers/pull/49/commits/39e0a647a5e114d468d13c712aa8fbdec7d189fb

**Comment by klipska** [comment]
Spatial and Temporal coverage are missing from the .xml

Spatial Coverage - 45 = pbcoreCoverage <coverageType>Spatial</coverageType>
Temporal Coverage - 46 = pbcoreCoverage <coverageType>Temporal</coverageType>
