### ISSUE TITLE
pbcorethat - need instructions to install and use

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#31]
We need instructions on how to install and use the next version.

**Comment by dericed** [comment]
sounds fine, i'll extend that out in the readme

**Comment by dericed** [comment]
partly resolved in https://github.com/cavpp/cavppers/pull/33/commits/9f3874008d82817377a46aa5b2bdc5cc8afdc650 https://github.com/cavpp/cavppers/pull/33/commits/4867cc1bc91a56a94d621d61690b072eb58af988

**Comment by klipska** [comment]
Can you add to the cavppers Read Me instructions on overall installation? Like I know we need to install homebrew first, then what we need to type in the command line to tap and install, and to update cavppers? How to update with new release after --HEAD install. 
Similarly I was thinking of pbcorethat instructions that indicate the expected directory structure, and files like AV data export from Islandora. Then what someone would need to type in the command line and what folder they should drag in. 
Is this more detail than you would normally but in the read me I can type up something that we save internally but it would be ideal for these instructions to exist in the same place as the script.

**Comment by dericed** [comment]
status?

**Comment by klipska** [comment]
It doesn't look like the Read Me [here](https://github.com/cavpp/cavppers/blob/master/README.md) has been updated with the specifics I was thinking of about but I can write something up for you to include there. Maybe Monday. My hope is just that the others at CA-R won't need to rely on my external instructions to find out how to install cavppers etc.

**Comment by klipska** [comment]
Ok, I added instructions to the ReadMe. I think this is good now.
