### ISSUE TITLE
pbcorethat - status update

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#32]
I just wanted to leave a comment here with an overview of what we need. 
Please resolve the open issues that I created after the test you sent around September. 
When you have a new version please tell us how to install it and I will do a more thorough test and add additional issues then!

I've send you some samples and mappings from the vendor via email over the last several months. Let me know if you need me to try to attach any of that to an issue here.

We also need a DC core script after the PBCore script is done, but I'm not sure if you have time for that. Let us know!

**Comment by dericed** [comment]
+1
